In [1]:
# Vectorization Example

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)
print(a,b)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0 
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

[0.58298047 0.10379041 0.70982015 ... 0.95925115 0.28184075 0.73118098] [0.63213855 0.93969634 0.12420228 ... 0.61080864 0.77614265 0.20539648]
250361.92918559894
Vectorized version: 1.194000244140625ms
250361.92918560648
For loop:508.5439682006836ms


In [4]:
# Broadcasting in Python

In [6]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0], 
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [8]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
#Python/Numpy Vectors

In [10]:
a = np.random.randn(5)

In [11]:
print(a)

[-0.51461122  0.13158657  0.48788267  1.36279205 -0.08323152]


In [12]:
print(a.shape)

(5,)


In [13]:
print(a.T)

[-0.51461122  0.13158657  0.48788267  1.36279205 -0.08323152]


In [14]:
print(np.dot(a, a.T))

2.384298899622043


In [15]:
# Best practice (5,1) or (1,5)
a = np.random.rand(5,1)
print(a)

[[0.24475031]
 [0.80368408]
 [0.16441647]
 [0.47821098]
 [0.03144442]]


In [16]:
print(a.T)

[[0.24475031 0.80368408 0.16441647 0.47821098 0.03144442]]


In [17]:
print(np.dot(a,a.T))

[[0.05990271 0.19670192 0.04024098 0.11704228 0.00769603]
 [0.19670192 0.6459081  0.1321389  0.38433055 0.02527138]
 [0.04024098 0.1321389  0.02703277 0.07862576 0.00516998]
 [0.11704228 0.38433055 0.07862576 0.22868574 0.01503707]
 [0.00769603 0.02527138 0.00516998 0.01503707 0.00098875]]


In [22]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [23]:
print(c.shape)

(12288, 45)


In [24]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [25]:
print(c)

[[ 1.64202125 -1.01943388 -2.31164408]
 [ 0.63156542 -0.09805494 -0.10906837]
 [-0.22861976 -0.78294947  0.06607201]]


In [26]:
print(c.shape)

(3, 3)


In [27]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [6]:
print(a, b, c.shape)

NameError: name 'a' is not defined

In [29]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [30]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [31]:
print(c.shape)

(12288, 45)


In [2]:
import numpy as np
A = np.random.rand(4,3)
B = np.sum(A, axis=1, keepdims = True)

In [3]:
print(B.shape)

(4, 1)


In [4]:
w1 = (4, 3)
b1 = (4, 1)
a0 = (2, 1)

In [8]:
wb = np.dot(w1, b1)

In [10]:
print(wb.shape)

()
